from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
_sym_db = _symbol_database.Default()
from ...substrait.ibis import algebra_pb2 as substrait_dot_ibis_dot_algebra__pb2
from ...substrait.ibis.extensions import extensions_pb2 as substrait_dot_ibis_dot_extensions_dot_extensions__pb2
DESCRIPTOR = _descriptor.FileDescriptor(name='substrait/ibis/plan.proto', package='substrait.ibis', syntax='proto3', serialized_options=b'\n\x17io.substrait.ibis.protoP\x01\xaa\x02\x17Substrait.Ibis.Protobuf', create_key=_descriptor._internal_create_key, serialized_pb=b'\n\x19substrait/ibis/plan.proto\x12\x0esubstrait.ibis\x1a\x1csubstrait/ibis/algebra.proto\x1a*substrait/ibis/extensions/extensions.proto"m\n\x07PlanRel\x12\'\n\x03rel\x18\x01 \x01(\x0b2\x13.substrait.ibis.RelH\x00R\x03rel\x12-\n\x04root\x18\x02 \x01(\x0b2\x17.substrait.ibis.RelRootH\x00R\x04rootB\n\n\x08rel_type"\xaa\x03\n\x04Plan\x121\n\x07version\x18\x06 \x01(\x0b2\x17.substrait.ibis.VersionR\x07version\x12T\n\x0eextension_uris\x18\x01 \x03(\x0b2-.substrait.ibis.extensions.SimpleExtensionURIR\rextensionUris\x12U\n\nextensions\x18\x02 \x03(\x0b25.substrait.ibis.extensions.SimpleExtensionDeclarationR\nextensions\x125\n\trelations\x18\x03 \x03(\x0b2\x17.substrait.ibis.PlanRelR\trelations\x12]\n\x13advanced_extensions\x18\x04 \x01(\x0b2,.substrait.ibis.extensions.AdvancedExtensionR\x12advancedExtensions\x12,\n\x12expected_type_urls\x18\x05 \x03(\tR\x10expectedTypeUrls"@\n\x0bPlanVersion\x121\n\x07version\x18\x06 \x01(\x0b2\x17.substrait.ibis.VersionR\x07version"\xa9\x01\n\x07Version\x12!\n\x0cmajor_number\x18\x01 \x01(\rR\x0bmajorNumber\x12!\n\x0cminor_number\x18\x02 \x01(\rR\x0bminorNumber\x12!\n\x0cpatch_number\x18\x03 \x01(\rR\x0bpatchNumber\x12\x19\n\x08git_hash\x18\x04 \x01(\tR\x07gitHash\x12\x1a\n\x08producer\x18\x05 \x01(\tR\x08producerB5\n\x17io.substrait.ibis.protoP\x01\xaa\x02\x17Substrait.Ibis.Protobufb\x06proto3', dependencies=[substrait_dot_ibis_dot_algebra__pb2.DESCRIPTOR, substrait_dot_ibis_dot_extensions_dot_extensions__pb2.DESCRIPTOR])
_PLANREL = _descriptor.Descriptor(name='PlanRel', full_name='substrait.ibis.PlanRel', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='rel', full_name='substrait.ibis.PlanRel.rel', index=0, number=1, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='rel', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='root', full_name='substrait.ibis.PlanRel.root', index=1, number=2, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='root', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[_descriptor.OneofDescriptor(name='rel_type', full_name='substrait.ibis.PlanRel.rel_type', index=0, containing_type=None, create_key=_descriptor._internal_create_key, fields=[])], serialized_start=119, serialized_end=228)
_PLAN = _descriptor.Descriptor(name='Plan', full_name='substrait.ibis.Plan', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='version', full_name='substrait.ibis.Plan.version', index=0, number=6, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='version', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='extension_uris', full_name='substrait.ibis.Plan.extension_uris', index=1, number=1, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='extensionUris', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='extensions', full_name='substrait.ibis.Plan.extensions', index=2, number=2, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='extensions', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='relations', full_name='substrait.ibis.Plan.relations', index=3, number=3, type=11, cpp_type=10, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='relations', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='advanced_extensions', full_name='substrait.ibis.Plan.advanced_extensions', index=4, number=4, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='advancedExtensions', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='expected_type_urls', full_name='substrait.ibis.Plan.expected_type_urls', index=5, number=5, type=9, cpp_type=9, label=3, has_default_value=False, default_value=[], message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='expectedTypeUrls', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=231, serialized_end=657)
_PLANVERSION = _descriptor.Descriptor(name='PlanVersion', full_name='substrait.ibis.PlanVersion', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='version', full_name='substrait.ibis.PlanVersion.version', index=0, number=6, type=11, cpp_type=10, label=1, has_default_value=False, default_value=None, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='version', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=659, serialized_end=723)
_VERSION = _descriptor.Descriptor(name='Version', full_name='substrait.ibis.Version', filename=None, file=DESCRIPTOR, containing_type=None, create_key=_descriptor._internal_create_key, fields=[_descriptor.FieldDescriptor(name='major_number', full_name='substrait.ibis.Version.major_number', index=0, number=1, type=13, cpp_type=3, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='majorNumber', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='minor_number', full_name='substrait.ibis.Version.minor_number', index=1, number=2, type=13, cpp_type=3, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='minorNumber', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='patch_number', full_name='substrait.ibis.Version.patch_number', index=2, number=3, type=13, cpp_type=3, label=1, has_default_value=False, default_value=0, message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='patchNumber', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='git_hash', full_name='substrait.ibis.Version.git_hash', index=3, number=4, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='gitHash', file=DESCRIPTOR, create_key=_descriptor._internal_create_key), _descriptor.FieldDescriptor(name='producer', full_name='substrait.ibis.Version.producer', index=4, number=5, type=9, cpp_type=9, label=1, has_default_value=False, default_value=b''.decode('utf-8'), message_type=None, enum_type=None, containing_type=None, is_extension=False, extension_scope=None, serialized_options=None, json_name='producer', file=DESCRIPTOR, create_key=_descriptor._internal_create_key)], extensions=[], nested_types=[], enum_types=[], serialized_options=None, is_extendable=False, syntax='proto3', extension_ranges=[], oneofs=[], serialized_start=726, serialized_end=895)
_PLANREL.fields_by_name['rel'].message_type = substrait_dot_ibis_dot_algebra__pb2._REL
_PLANREL.fields_by_name['root'].message_type = substrait_dot_ibis_dot_algebra__pb2._RELROOT
_PLANREL.oneofs_by_name['rel_type'].fields.append(_PLANREL.fields_by_name['rel'])
_PLANREL.fields_by_name['rel'].containing_oneof = _PLANREL.oneofs_by_name['rel_type']
_PLANREL.oneofs_by_name['rel_type'].fields.append(_PLANREL.fields_by_name['root'])
_PLANREL.fields_by_name['root'].containing_oneof = _PLANREL.oneofs_by_name['rel_type']
_PLAN.fields_by_name['version'].message_type = _VERSION
_PLAN.fields_by_name['extension_uris'].message_type = substrait_dot_ibis_dot_extensions_dot_extensions__pb2._SIMPLEEXTENSIONURI
_PLAN.fields_by_name['extensions'].message_type = substrait_dot_ibis_dot_extensions_dot_extensions__pb2._SIMPLEEXTENSIONDECLARATION
_PLAN.fields_by_name['relations'].message_type = _PLANREL
_PLAN.fields_by_name['advanced_extensions'].message_type = substrait_dot_ibis_dot_extensions_dot_extensions__pb2._ADVANCEDEXTENSION
_PLANVERSION.fields_by_name['version'].message_type = _VERSION
DESCRIPTOR.message_types_by_name['PlanRel'] = _PLANREL
DESCRIPTOR.message_types_by_name['Plan'] = _PLAN
DESCRIPTOR.message_types_by_name['PlanVersion'] = _PLANVERSION
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)
PlanRel = _reflection.GeneratedProtocolMessageType('PlanRel', (_message.Message,), {'DESCRIPTOR': _PLANREL, '__module__': 'substrait.ibis.plan_pb2'})
_sym_db.RegisterMessage(PlanRel)
Plan = _reflection.GeneratedProtocolMessageType('Plan', (_message.Message,), {'DESCRIPTOR': _PLAN, '__module__': 'substrait.ibis.plan_pb2'})
_sym_db.RegisterMessage(Plan)
PlanVersion = _reflection.GeneratedProtocolMessageType('PlanVersion', (_message.Message,), {'DESCRIPTOR': _PLANVERSION, '__module__': 'substrait.ibis.plan_pb2'})
_sym_db.RegisterMessage(PlanVersion)
Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {'DESCRIPTOR': _VERSION, '__module__': 'substrait.ibis.plan_pb2'})
_sym_db.RegisterMessage(Version)
DESCRIPTOR._options = None